### ISSUE TITLE
ModuleNotFoundError: No module named 'vica'

### ISSUE THREAD

**Issue by qingpeng** [USDA-ARS-GBRU/vica#1]
(py36) qpzhang@genepool14:~/Github/vica/vica$ ./vica_cli.py
Traceback (most recent call last):
  File "./vica_cli.py", line 14, in <module>
    import vica
ModuleNotFoundError: No module named 'vica'

Is this related to something about Python3?

https://stackoverflow.com/questions/43728431/modulenotfounderror-no-module-named-x

**Comment by arivers** [comment]
How did you install vica? 

Did you run `python setup.py build` then install locally with pip `pip install -e .` ?

**Comment by qingpeng** [comment]
I tried:
python setup.py build -e .

**Comment by arivers** [comment]
You should put in a NERSC support ticket. I had issues installing that had to do with how they handled modules. Dan can help you.

Here are commands to install it in a conda environment on nersc:
```bash
   module unload python
   module load python/3.6-anaconda_4.3.0
   module load bbtools
   module load pigz
   module load prodigal
   conda create -n vicaenv python=3.6
   source activate vicaenv
   conda config --add channels bioconda
   conda install pyfaidx 
   conda install khmer
   git clone https://github.com/USDA-ARS-GBRU/vica.git
   python setup.py build
   pip install -e .
```

**Comment by arivers** [comment]
Pushed a new version  to pip.  I can now install on Genepool.
